baseURL = "https://marcdepalol.netlify.com"
languageCode = "en-us"
title = "Marc de Palol's notes"
theme = "yinyang"


[params]
headTitle = "Marc de Palol's notes"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-16677708-2"></script>'

[[params.socials]]
name = "Github"
link = "https://github.com/lant"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/lant"

[[params.socials]]
name = "About"
link = "https://marcdepalol.netlify.com/about/"
